# Generated by Django 2.2.2 on 2020-02-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lname',
        ),
    ]
